image: node:latest

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL#https?}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/packages/npm/:_authToken=${CORE_PL_MODULES_REGISTRY_TOKEN}"
        echo "${CI_API_V4_URL#https?}/projects/:_authToken=${CORE_PL_MODULES_REGISTRY_TOKEN}"
      } | tee -a .npmrc
    - yarn config set userconfig .npmrc
    - yarn && yarn build
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - npm publish --userconfig .npmrc
